name: Pruebas unitarias y funcionales

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Cargar esquema de la base de datos
        run: |
          psql -h localhost -U postgres -d testdb -f scripts.sql  2>&1 | tee sql_log.txt 
        env:
          PGPASSWORD: postgres

      - name: Test tables creation
        run: |
          if [ $(grep -c "CREATE TABLE" sql_log.txt) -lt 4 ] sql_log.txt; then
            exit 1
          fi          
